__version__:
  serializer: 1
  data: 10
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 4.67056717778426
        Brightness: 1.8
        ExposureTime: 6500
        Gain: 1.10814070061623
    - Acquisition:
        Aperture: 3.32906716329996
        Brightness: 1.8
        ExposureTime: 6500
        Gain: 1.80729900199487
    - Acquisition:
        Aperture: 2.4636050983726
        Brightness: 1.8
        ExposureTime: 6500
        Gain: 3.17691510948466
    - Acquisition:
        Aperture: 2.14684583945452
        Brightness: 1.8
        ExposureTime: 13000
        Gain: 4.05768483758939
  Diagnostics:
    Enabled: no
  Experimental:
    Engine: phase
  Processing:
    Color:
      Balance:
        Blue: 2.5
        Green: 1
        Red: 2
      Experimental:
        ToneMapping:
          Enabled: hdrOnly
      Gamma: 1.5
    Filters:
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: yes
            Strength: 0.3
          Removal:
            Enabled: no
            Threshold: 0.5
      Noise:
        Removal:
          Enabled: yes
          Threshold: 15
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 18
      Reflection:
        Removal:
          Enabled: yes
      Smoothing:
        Gaussian:
          Enabled: no
          Sigma: 3.25
