__version__:
  serializer: 1
  data: 10
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 2
        Brightness: 1.8
        ExposureTime: 1677
        Gain: 1.16658382659394
    - Acquisition:
        Aperture: 5.93387497820844
        Brightness: 1.76080864385791
        ExposureTime: 1677
        Gain: 1
    - Acquisition:
        Aperture: 2
        Brightness: 1.79999999999997
        ExposureTime: 18447
        Gain: 1.87614204252087
    - Acquisition:
        Aperture: 2
        Brightness: 1.79999999999997
        ExposureTime: 18447
        Gain: 1.87614204252087
  Diagnostics:
    Enabled: no
  Experimental:
    Engine: phase
  Processing:
    Color:
      Balance:
        Blue: 3.2
        Green: 1
        Red: 2
      Experimental:
        ToneMapping:
          Enabled: always
      Gamma: 1
    Filters:
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: yes
            Strength: 0.3
          Removal:
            Enabled: no
            Threshold: 0.2
      Noise:
        Removal:
          Enabled: yes
          Threshold: 5
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 21
      Reflection:
        Removal:
          Enabled: yes
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 1
