__version__:
  serializer: 1
  data: 10
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 2.59367910930202
        Brightness: 1.6
        ExposureTime: 15000
        Gain: 1
    - Acquisition:
        Aperture: 2.37841423000544
        Brightness: 1.6
        ExposureTime: 10000
        Gain: 1.3
  Diagnostics:
    Enabled: no
  Experimental:
    Engine: phase
  Processing:
    Color:
      Balance:
        Blue: 1.1
        Green: 1.06
        Red: 1.08
      Experimental:
        ToneMapping:
          Enabled: always
      Gamma: 1
    Filters:
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: yes
            Strength: 0.3
          Removal:
            Enabled: no
            Threshold: 0.2
      Noise:
        Removal:
          Enabled: yes
          Threshold: 5
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 10
      Reflection:
        Removal:
          Enabled: yes
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 1
